### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by jonpalmisc** [jwmza/polymath#1]
Hey!

I was really looking forward to seeing this project get released and grow. I apologize for opening an issue here but I couldn't find an email for you on your website. Are there updates regarding this project you can share?

Thanks!

**Comment by jrysana** [comment]
Hey @jonpalmisc , no need to apologize! I'll send you an email directly, but there should also be an email going out to the mailing list shortly. Progress has been slowed and often delayed throughout the year, and a lot is still undecided in terms of establishing a lasting syntax, which I would like to have in place before a 1.0 release in order to avoid breaking changes to old files as the project grows over time.

That being said, I'd like to open up the development soon and engage with everybody who is interested in the project.

Thank you for your interest and patience :)
